#pragma once
#include <wiringPi.h>
#include <softPwm.h>
#include <stdlib.h>
#include <stdint.h>
#include <iostream>
#include <cmath>
#include <thread>
#include <chrono>
#include <cstdlib>
#include <atomic>
